-- Esquema inicial de Cuquora CRM.
-- SQL compatible con H2 (local y tests) y PostgreSQL (Docker).
-- Los enums se guardan como texto (@Enumerated(EnumType.STRING)) con un CHECK de valores válidos.

CREATE TABLE centers (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    address   VARCHAR(255),
    phone     VARCHAR(255),
    email     VARCHAR(255),
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

CREATE TABLE users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255),
    phone     VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255) NOT NULL,
    center_id BIGINT,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('CLIENT', 'WORKER')),
    CONSTRAINT fk_users_center FOREIGN KEY (center_id) REFERENCES centers (id)
);

CREATE TABLE treatments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR(1000),
    price          DOUBLE PRECISION NOT NULL,
    duration       INTEGER NOT NULL,
    treatment_type VARCHAR(255) NOT NULL,
    center_id      BIGINT NOT NULL,
    CONSTRAINT ck_treatments_type CHECK (treatment_type IN
        ('MANICURA_PEDICURA', 'FACIAL', 'CORPORAL', 'MASAJES', 'PELUQUERIA', 'DEPILACION', 'OTRO')),
    CONSTRAINT fk_treatments_center FOREIGN KEY (center_id) REFERENCES centers (id)
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    category    VARCHAR(255),
    price       DOUBLE PRECISION NOT NULL
);

CREATE TABLE inventories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id  BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    stock      INTEGER NOT NULL,
    CONSTRAINT uk_inventories_center_product UNIQUE (center_id, product_id),
    CONSTRAINT fk_inventories_center FOREIGN KEY (center_id) REFERENCES centers (id),
    CONSTRAINT fk_inventories_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE appointments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time      TIMESTAMP(6) NOT NULL,
    treatment_id   BIGINT NOT NULL,
    center_id      BIGINT NOT NULL,
    client_id      BIGINT,
    guest_name     VARCHAR(255),
    guest_phone    VARCHAR(255),
    worker_id      BIGINT,
    status         VARCHAR(255) NOT NULL,
    worker_message VARCHAR(500),
    CONSTRAINT ck_appointments_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'COMPLETED')),
    CONSTRAINT fk_appointments_treatment FOREIGN KEY (treatment_id) REFERENCES treatments (id),
    CONSTRAINT fk_appointments_center FOREIGN KEY (center_id) REFERENCES centers (id),
    CONSTRAINT fk_appointments_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_worker FOREIGN KEY (worker_id) REFERENCES users (id)
);

CREATE TABLE client_cards (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id     BIGINT NOT NULL,
    client_id     BIGINT,
    guest_name    VARCHAR(255),
    guest_phone   VARCHAR(255),
    data_json     TEXT,
    updated_at    TIMESTAMP(6),
    updated_by_id BIGINT,
    CONSTRAINT fk_client_cards_center FOREIGN KEY (center_id) REFERENCES centers (id),
    CONSTRAINT fk_client_cards_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_client_cards_updated_by FOREIGN KEY (updated_by_id) REFERENCES users (id)
);

CREATE TABLE client_card_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id   BIGINT NOT NULL,
    fields_json TEXT NOT NULL,
    CONSTRAINT uk_client_card_templates_center UNIQUE (center_id),
    CONSTRAINT fk_client_card_templates_center FOREIGN KEY (center_id) REFERENCES centers (id)
);

-- Índices para las consultas más frecuentes (agenda, panel y búsquedas por centro)
CREATE INDEX idx_appointments_date_time ON appointments (date_time);
CREATE INDEX idx_appointments_center ON appointments (center_id);
CREATE INDEX idx_appointments_worker ON appointments (worker_id);
CREATE INDEX idx_appointments_client ON appointments (client_id);
CREATE INDEX idx_appointments_status ON appointments (status);
CREATE INDEX idx_treatments_center ON treatments (center_id);
CREATE INDEX idx_inventories_product ON inventories (product_id);
CREATE INDEX idx_client_cards_center_client ON client_cards (center_id, client_id);
